import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ar' | 'hi';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'app.name': 'Karate Academy',
    'app.subtitle': 'Attendance Manager',
    'nav.dashboard': 'Dashboard',
    'nav.students': 'Students',
    'nav.attendance': 'Attendance',
    'nav.packages': 'Packages',
    'nav.branches': 'Branches',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    'nav.schemes': 'Schemes',
    'nav.stock': 'Stock',
    'nav.sales': 'Sales',
    'nav.invoices': 'Invoices',
    'nav.users': 'Users',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full Name',
    'auth.role': 'Role',
    'auth.branch': 'Branch',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.resetPassword': 'Reset Password',
    'auth.backToLogin': 'Back to Login',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'dashboard.welcome': 'Welcome',
    'dashboard.totalStudents': 'Total Students',
    'dashboard.totalBranches': 'Total Branches',
    'dashboard.todayAttendance': 'Today Attendance',
    'dashboard.activePackages': 'Active Packages',
    'dashboard.expiringPackages': 'Expiring Soon',
    'students.title': 'Students',
    'students.add': 'Add Student',
    'students.search': 'Search students...',
    'students.name': 'Name',
    'students.phone': 'Phone',
    'students.nationality': 'Nationality',
    'students.address': 'Address',
    'students.package': 'Package',
    'students.branch': 'Branch',
    'students.status': 'Status',
    'students.active': 'Active',
    'students.inactive': 'Inactive',
    'students.actions': 'Actions',
    'students.edit': 'Edit',
    'students.delete': 'Delete',
    'students.packageStart': 'Package Start',
    'students.packageEnd': 'Package End',
    'students.notes': 'Notes',
    'attendance.title': 'Attendance',
    'attendance.mark': 'Mark Attendance',
    'attendance.date': 'Date',
    'attendance.student': 'Student',
    'attendance.status': 'Status',
    'attendance.present': 'Present',
    'attendance.absent': 'Absent',
    'attendance.late': 'Late',
    'attendance.note': 'Note',
    'attendance.markedBy': 'Marked By',
    'attendance.history': 'Attendance History',
    'packages.title': 'Packages',
    'packages.add': 'Add Package',
    'packages.name': 'Package Name',
    'packages.sessionsPerMonth': 'Sessions/Month',
    'packages.sessionsPerWeek': 'Sessions/Week',
    'packages.price': 'Price',
    'packages.description': 'Description',
    'branches.title': 'Branches',
    'branches.add': 'Add Branch',
    'branches.name': 'Branch Name',
    'branches.location': 'Location',
    'reports.title': 'Reports',
    'reports.export': 'Export',
    'reports.filter': 'Filter',
    'reports.dateRange': 'Date Range',
    'reports.from': 'From',
    'reports.to': 'To',
    'settings.title': 'Settings',
    'settings.academyName': 'Academy Name',
    'settings.logo': 'Logo',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications',
    'settings.theme': 'Theme',
    'settings.save': 'Save',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.add': 'Add',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.loading': 'Loading...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.view': 'View',
    'common.notes': 'Notes',
    'common.export': 'Export',
    'common.actions': 'Actions',
    'role.super_admin': 'Super Admin',
    'role.branch_manager': 'Branch Manager',
    'role.coach': 'Coach',
    'role.stock_manager': 'Stock Manager',
    'role.accountant': 'Accountant',
    'invoices.title': 'Invoices',
    'invoices.invoice': 'INVOICE',
    'invoices.invoiceNumber': 'Invoice Number',
    'invoices.invoiceDetails': 'Invoice Details',
    'invoices.date': 'Date',
    'invoices.customer': 'Customer',
    'invoices.branch': 'Branch',
    'invoices.total': 'Total',
    'invoices.paymentMethod': 'Payment Method',
    'invoices.paymentStatus': 'Payment Status',
    'invoices.status': 'Status',
    'invoices.search': 'Search invoices...',
    'invoices.allBranches': 'All Branches',
    'invoices.allPaymentMethods': 'All Payment Methods',
    'invoices.allStatuses': 'All Statuses',
    'invoices.dateFrom': 'Date From',
    'invoices.dateTo': 'Date To',
    'invoices.totalRevenue': 'Total Revenue',
    'invoices.totalPaid': 'Total Paid',
    'invoices.totalPending': 'Total Pending',
    'invoices.noInvoices': 'No invoices found',
    'invoices.billTo': 'Bill To',
    'invoices.item': 'Item',
    'invoices.quantity': 'Quantity',
    'invoices.unitPrice': 'Unit Price',
    'invoices.subtotal': 'Subtotal',
    'invoices.vat': 'VAT',
    'invoices.amountPaid': 'Amount Paid',
    'invoices.thankYou': 'Thank you for your business!',
    'sales.cash': 'Cash',
    'sales.card': 'Card',
    'sales.installment': 'Installment',
    'sales.paid': 'Paid',
    'sales.pending': 'Pending',
    'sales.partial': 'Partial',
    'settings.taxNumber': 'Tax Registration Number',
    'nav.stockInventory': 'Stock Inventory',
    'stockInventory.title': 'Stock Inventory Management',
    'stockInventory.subtitle': 'Track stock counts and sales reports',
    'stockInventory.stockCount': 'Stock Count',
    'stockInventory.salesReport': 'Sales Report',
    'stockInventory.item': 'Item',
    'stockInventory.allItems': 'All Items',
    'stockInventory.startDate': 'Start Date',
    'stockInventory.endDate': 'End Date',
    'stockInventory.loadReport': 'Load Report',
    'stockInventory.newStockCount': 'New Stock Count',
    'stockInventory.exportCSV': 'Export to CSV',
    'stockInventory.date': 'Date',
    'stockInventory.systemQty': 'System Qty',
    'stockInventory.actualQty': 'Actual Qty',
    'stockInventory.difference': 'Difference',
    'stockInventory.notes': 'Notes',
    'stockInventory.status': 'Status',
    'stockInventory.noRecords': 'No stock counts recorded yet',
    'stockInventory.customer': 'Customer',
    'stockInventory.itemName': 'Item Name',
    'stockInventory.quantity': 'Quantity',
    'stockInventory.unitPrice': 'Unit Price',
    'stockInventory.total': 'Total',
    'stockInventory.noSalesData': 'No sales data. Click "Load Report" to fetch data.',
    'stockInventory.totalQtySold': 'Total Quantity Sold',
    'stockInventory.totalSalesAmount': 'Total Sales Amount',
    'stockInventory.recordStockCount': 'Record Stock Count',
    'stockInventory.selectItem': 'Select item...',
    'stockInventory.actualQuantity': 'Actual Quantity',
    'stockInventory.systemQuantity': 'System Quantity',
    'stockInventory.reasonNotes': 'Reason for difference, location checked, etc...',
    'stockInventory.saveCount': 'Save Count',
  },
  ar: {
    'app.name': 'أكاديمية الكاراتيه',
    'app.subtitle': 'إدارة الحضور',
    'nav.dashboard': 'لوحة التحكم',
    'nav.students': 'الطلاب',
    'nav.attendance': 'الحضور',
    'nav.packages': 'الباقات',
    'nav.branches': 'الفروع',
    'nav.reports': 'التقارير',
    'nav.settings': 'الإعدادات',
    'nav.logout': 'تسجيل الخروج',
    'nav.schemes': 'الأحزمة',
    'nav.stock': 'المخزون',
    'nav.sales': 'المبيعات',
    'nav.invoices': 'الفواتير',
    'nav.users': 'المستخدمون',
    'auth.login': 'تسجيل الدخول',
    'auth.signup': 'إنشاء حساب',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.fullName': 'الاسم الكامل',
    'auth.role': 'الدور',
    'auth.branch': 'الفرع',
    'auth.forgotPassword': 'نسيت كلمة المرور؟',
    'auth.resetPassword': 'إعادة تعيين كلمة المرور',
    'auth.backToLogin': 'العودة لتسجيل الدخول',
    'auth.noAccount': 'ليس لديك حساب؟',
    'auth.hasAccount': 'لديك حساب بالفعل؟',
    'dashboard.welcome': 'مرحباً',
    'dashboard.totalStudents': 'إجمالي الطلاب',
    'dashboard.totalBranches': 'إجمالي الفروع',
    'dashboard.todayAttendance': 'حضور اليوم',
    'dashboard.activePackages': 'الباقات النشطة',
    'dashboard.expiringPackages': 'تنتهي قريباً',
    'students.title': 'الطلاب',
    'students.add': 'إضافة طالب',
    'students.search': 'البحث عن طالب...',
    'students.name': 'الاسم',
    'students.phone': 'الهاتف',
    'students.nationality': 'الجنسية',
    'students.address': 'العنوان',
    'students.package': 'الباقة',
    'students.branch': 'الفرع',
    'students.status': 'الحالة',
    'students.active': 'نشط',
    'students.inactive': 'غير نشط',
    'students.actions': 'الإجراءات',
    'students.edit': 'تعديل',
    'students.delete': 'حذف',
    'students.packageStart': 'بداية الباقة',
    'students.packageEnd': 'نهاية الباقة',
    'students.notes': 'ملاحظات',
    'attendance.title': 'الحضور',
    'attendance.mark': 'تسجيل الحضور',
    'attendance.date': 'التاريخ',
    'attendance.student': 'الطالب',
    'attendance.status': 'الحالة',
    'attendance.present': 'حاضر',
    'attendance.absent': 'غائب',
    'attendance.late': 'متأخر',
    'attendance.note': 'ملاحظة',
    'attendance.markedBy': 'سجل بواسطة',
    'attendance.history': 'سجل الحضور',
    'packages.title': 'الباقات',
    'packages.add': 'إضافة باقة',
    'packages.name': 'اسم الباقة',
    'packages.sessionsPerMonth': 'جلسات/شهر',
    'packages.sessionsPerWeek': 'جلسات/أسبوع',
    'packages.price': 'السعر',
    'packages.description': 'الوصف',
    'branches.title': 'الفروع',
    'branches.add': 'إضافة فرع',
    'branches.name': 'اسم الفرع',
    'branches.location': 'الموقع',
    'reports.title': 'التقارير',
    'reports.export': 'تصدير',
    'reports.filter': 'تصفية',
    'reports.dateRange': 'نطاق التاريخ',
    'reports.from': 'من',
    'reports.to': 'إلى',
    'settings.title': 'الإعدادات',
    'settings.academyName': 'اسم الأكاديمية',
    'settings.logo': 'الشعار',
    'settings.language': 'اللغة',
    'settings.notifications': 'الإشعارات',
    'settings.theme': 'المظهر',
    'settings.save': 'حفظ',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.add': 'إضافة',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.all': 'الكل',
    'common.loading': 'جاري التحميل...',
    'common.success': 'نجح',
    'common.error': 'خطأ',
    'common.view': 'عرض',
    'common.notes': 'ملاحظات',
    'common.export': 'تصدير',
    'common.actions': 'الإجراءات',
    'role.super_admin': 'مدير عام',
    'role.branch_manager': 'مدير فرع',
    'role.coach': 'مدرب',
    'role.stock_manager': 'مدير المخزون',
    'role.accountant': 'محاسب',
    'invoices.title': 'الفواتير',
    'invoices.invoice': 'فاتورة',
    'invoices.invoiceNumber': 'رقم الفاتورة',
    'invoices.invoiceDetails': 'تفاصيل الفاتورة',
    'invoices.date': 'التاريخ',
    'invoices.customer': 'العميل',
    'invoices.branch': 'الفرع',
    'invoices.total': 'المجموع',
    'invoices.paymentMethod': 'طريقة الدفع',
    'invoices.paymentStatus': 'حالة الدفع',
    'invoices.status': 'الحالة',
    'invoices.search': 'البحث في الفواتير...',
    'invoices.allBranches': 'كل الفروع',
    'invoices.allPaymentMethods': 'كل طرق الدفع',
    'invoices.allStatuses': 'كل الحالات',
    'invoices.dateFrom': 'من تاريخ',
    'invoices.dateTo': 'إلى تاريخ',
    'invoices.totalRevenue': 'إجمالي الإيرادات',
    'invoices.totalPaid': 'إجمالي المدفوع',
    'invoices.totalPending': 'إجمالي المعلق',
    'invoices.noInvoices': 'لا توجد فواتير',
    'invoices.billTo': 'إلى',
    'invoices.item': 'الصنف',
    'invoices.quantity': 'الكمية',
    'invoices.unitPrice': 'السعر',
    'invoices.subtotal': 'المجموع الفرعي',
    'invoices.vat': 'ضريبة القيمة المضافة',
    'invoices.amountPaid': 'المبلغ المدفوع',
    'invoices.thankYou': 'شكراً لتعاملكم معنا!',
    'sales.cash': 'نقد',
    'sales.card': 'بطاقة',
    'sales.installment': 'تقسيط',
    'sales.paid': 'مدفوع',
    'sales.pending': 'معلق',
    'sales.partial': 'جزئي',
    'settings.taxNumber': 'رقم السجل الضريبي',
    'nav.stockInventory': 'جرد المخزون',
    'stockInventory.title': 'إدارة جرد المخزون',
    'stockInventory.subtitle': 'تتبع عدد المخزون وتقارير المبيعات',
    'stockInventory.stockCount': 'عدد المخزون',
    'stockInventory.salesReport': 'تقرير المبيعات',
    'stockInventory.item': 'الصنف',
    'stockInventory.allItems': 'جميع الأصناف',
    'stockInventory.startDate': 'تاريخ البداية',
    'stockInventory.endDate': 'تاريخ النهاية',
    'stockInventory.loadReport': 'تحميل التقرير',
    'stockInventory.newStockCount': 'عدد مخزون جديد',
    'stockInventory.exportCSV': 'تصدير إلى CSV',
    'stockInventory.date': 'التاريخ',
    'stockInventory.systemQty': 'الكمية بالنظام',
    'stockInventory.actualQty': 'الكمية الفعلية',
    'stockInventory.difference': 'الفرق',
    'stockInventory.notes': 'ملاحظات',
    'stockInventory.status': 'الحالة',
    'stockInventory.noRecords': 'لم يتم تسجيل أي عدد للمخزون بعد',
    'stockInventory.customer': 'العميل',
    'stockInventory.itemName': 'اسم الصنف',
    'stockInventory.quantity': 'الكمية',
    'stockInventory.unitPrice': 'سعر الوحدة',
    'stockInventory.total': 'المجموع',
    'stockInventory.noSalesData': 'لا توجد بيانات مبيعات. انقر على "تحميل التقرير" لجلب البيانات.',
    'stockInventory.totalQtySold': 'إجمالي الكمية المباعة',
    'stockInventory.totalSalesAmount': 'إجمالي مبلغ المبيعات',
    'stockInventory.recordStockCount': 'تسجيل عدد المخزون',
    'stockInventory.selectItem': 'اختر صنف...',
    'stockInventory.actualQuantity': 'الكمية الفعلية',
    'stockInventory.systemQuantity': 'الكمية بالنظام',
    'stockInventory.reasonNotes': 'سبب الاختلاف، الموقع الذي تم فحصه، إلخ...',
    'stockInventory.saveCount': 'حفظ العدد',
  },
  hi: {
    'app.name': 'कराटे अकादमी',
    'app.subtitle': 'उपस्थिति प्रबंधक',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.students': 'छात्र',
    'nav.attendance': 'उपस्थिति',
    'nav.packages': 'पैकेज',
    'nav.branches': 'शाखाएँ',
    'nav.reports': 'रिपोर्ट',
    'nav.settings': 'सेटिंग',
    'nav.logout': 'लॉग आउट',
    'nav.schemes': 'योजनाएँ',
    'nav.stock': 'स्टॉक',
    'nav.sales': 'बिक्री',
    'nav.invoices': 'चालान',
    'nav.users': 'उपयोगकर्ता',
    'auth.login': 'लॉग इन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.fullName': 'पूरा नाम',
    'auth.role': 'भूमिका',
    'auth.branch': 'शाखा',
    'auth.forgotPassword': 'पासवर्ड भूल गए?',
    'auth.resetPassword': 'पासवर्ड रीसेट करें',
    'auth.backToLogin': 'लॉगिन पर वापस जाएं',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.hasAccount': 'पहले से खाता है?',
    'dashboard.welcome': 'स्वागत',
    'dashboard.totalStudents': 'कुल छात्र',
    'dashboard.totalBranches': 'कुल शाखाएँ',
    'dashboard.todayAttendance': 'आज की उपस्थिति',
    'dashboard.activePackages': 'सक्रिय पैकेज',
    'dashboard.expiringPackages': 'जल्द समाप्त हो रहे',
    'students.title': 'छात्र',
    'students.add': 'छात्र जोड़ें',
    'students.search': 'छात्र खोजें...',
    'students.name': 'नाम',
    'students.phone': 'फोन',
    'students.nationality': 'राष्ट्रीयता',
    'students.address': 'पता',
    'students.package': 'पैकेज',
    'students.branch': 'शाखा',
    'students.status': 'स्थिति',
    'students.active': 'सक्रिय',
    'students.inactive': 'निष्क्रिय',
    'students.actions': 'क्रियाएं',
    'students.edit': 'संपादित करें',
    'students.delete': 'हटाएं',
    'students.packageStart': 'पैकेज शुरू',
    'students.packageEnd': 'पैकेज समाप्त',
    'students.notes': 'नोट्स',
    'attendance.title': 'उपस्थिति',
    'attendance.mark': 'उपस्थिति चिह्नित करें',
    'attendance.date': 'तारीख',
    'attendance.student': 'छात्र',
    'attendance.status': 'स्थिति',
    'attendance.present': 'उपस्थित',
    'attendance.absent': 'अनुपस्थित',
    'attendance.late': 'देर से',
    'attendance.note': 'नोट',
    'attendance.markedBy': 'द्वारा चिह्नित',
    'attendance.history': 'उपस्थिति इतिहास',
    'packages.title': 'पैकेज',
    'packages.add': 'पैकेज जोड़ें',
    'packages.name': 'पैकेज का नाम',
    'packages.sessionsPerMonth': 'सत्र/महीना',
    'packages.sessionsPerWeek': 'सत्र/सप्ताह',
    'packages.price': 'कीमत',
    'packages.description': 'विवरण',
    'branches.title': 'शाखाएँ',
    'branches.add': 'शाखा जोड़ें',
    'branches.name': 'शाखा का नाम',
    'branches.location': 'स्थान',
    'reports.title': 'रिपोर्ट',
    'reports.export': 'निर्यात',
    'reports.filter': 'फिल्टर',
    'reports.dateRange': 'तिथि सीमा',
    'reports.from': 'से',
    'reports.to': 'तक',
    'settings.title': 'सेटिंग',
    'settings.academyName': 'अकादमी का नाम',
    'settings.logo': 'लोगो',
    'settings.language': 'भाषा',
    'settings.notifications': 'सूचनाएं',
    'settings.theme': 'थीम',
    'settings.save': 'सहेजें',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.add': 'जोड़ें',
    'common.search': 'खोजें',
    'common.filter': 'फिल्टर',
    'common.all': 'सभी',
    'common.loading': 'लोड हो रहा है...',
    'common.success': 'सफलता',
    'common.error': 'त्रुटि',
    'common.view': 'देखें',
    'common.notes': 'नोट्स',
    'common.export': 'निर्यात',
    'common.actions': 'क्रियाएं',
    'role.super_admin': 'सुपर एडमिन',
    'role.branch_manager': 'शाखा प्रबंधक',
    'role.coach': 'कोच',
    'role.stock_manager': 'स्टॉक प्रबंधक',
    'role.accountant': 'लेखाकार',
    'invoices.title': 'चालान',
    'invoices.invoice': 'चालान',
    'invoices.invoiceNumber': 'चालान संख्या',
    'invoices.invoiceDetails': 'चालान विवरण',
    'invoices.date': 'तारीख',
    'invoices.customer': 'ग्राहक',
    'invoices.branch': 'शाखा',
    'invoices.total': 'कुल',
    'invoices.paymentMethod': 'भुगतान विधि',
    'invoices.paymentStatus': 'भुगतान स्थिति',
    'invoices.status': 'स्थिति',
    'invoices.search': 'चालान खोजें...',
    'invoices.allBranches': 'सभी शाखाएँ',
    'invoices.allPaymentMethods': 'सभी भुगतान विधियाँ',
    'invoices.allStatuses': 'सभी स्थितियाँ',
    'invoices.dateFrom': 'तारीख से',
    'invoices.dateTo': 'तारीख तक',
    'invoices.totalRevenue': 'कुल राजस्व',
    'invoices.totalPaid': 'कुल भुगतान',
    'invoices.totalPending': 'कुल बकाया',
    'invoices.noInvoices': 'कोई चालान नहीं मिला',
    'invoices.billTo': 'को बिल',
    'invoices.item': 'वस्तु',
    'invoices.quantity': 'मात्रा',
    'invoices.unitPrice': 'इकाई मूल्य',
    'invoices.subtotal': 'उप-योग',
    'invoices.vat': 'वैट',
    'invoices.amountPaid': 'भुगतान राशि',
    'invoices.thankYou': 'आपके व्यापार के लिए धन्यवाद!',
    'sales.cash': 'नकद',
    'sales.card': 'कार्ड',
    'sales.installment': 'किस्त',
    'sales.paid': 'भुगतान किया',
    'sales.pending': 'लंबित',
    'sales.partial': 'आंशिक',
    'settings.taxNumber': 'कर पंजीकरण संख्या',
    'nav.stockInventory': 'स्टॉक इन्वेंटरी',
    'stockInventory.title': 'स्टॉक इन्वेंटरी प्रबंधन',
    'stockInventory.subtitle': 'स्टॉक गणना और बिक्री रिपोर्ट ट्रैक करें',
    'stockInventory.stockCount': 'स्टॉक गणना',
    'stockInventory.salesReport': 'बिक्री रिपोर्ट',
    'stockInventory.item': 'वस्तु',
    'stockInventory.allItems': 'सभी वस्तुएं',
    'stockInventory.startDate': 'आरंभ तिथि',
    'stockInventory.endDate': 'अंतिम तिथि',
    'stockInventory.loadReport': 'रिपोर्ट लोड करें',
    'stockInventory.newStockCount': 'नई स्टॉक गणना',
    'stockInventory.exportCSV': 'CSV में निर्यात करें',
    'stockInventory.date': 'तारीख',
    'stockInventory.systemQty': 'सिस्टम मात्रा',
    'stockInventory.actualQty': 'वास्तविक मात्रा',
    'stockInventory.difference': 'अंतर',
    'stockInventory.notes': 'नोट्स',
    'stockInventory.status': 'स्थिति',
    'stockInventory.noRecords': 'अभी तक कोई स्टॉक गणना दर्ज नहीं की गई',
    'stockInventory.customer': 'ग्राहक',
    'stockInventory.itemName': 'वस्तु का नाम',
    'stockInventory.quantity': 'मात्रा',
    'stockInventory.unitPrice': 'इकाई मूल्य',
    'stockInventory.total': 'कुल',
    'stockInventory.noSalesData': 'कोई बिक्री डेटा नहीं। डेटा लाने के लिए "रिपोर्ट लोड करें" पर क्लिक करें।',
    'stockInventory.totalQtySold': 'कुल बेची गई मात्रा',
    'stockInventory.totalSalesAmount': 'कुल बिक्री राशि',
    'stockInventory.recordStockCount': 'स्टॉक गणना रिकॉर्ड करें',
    'stockInventory.selectItem': 'वस्तु चुनें...',
    'stockInventory.actualQuantity': 'वास्तविक मात्रा',
    'stockInventory.systemQuantity': 'सिस्टम मात्रा',
    'stockInventory.reasonNotes': 'अंतर का कारण, जांची गई स्थिति, आदि...',
    'stockInventory.saveCount': 'गणना सहेजें',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && ['en', 'ar', 'hi'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
